// Six homes on Banksia Street, Wattlebrook.
// saleType 'auction': guide = advertised range (underquoted, as is tradition), reserve = vendor's number.
// saleType 'private': asking = advertised price, vendorMin = what they'd actually sign at.
// trueValue = what it's really worth. repairCost = defects a building & pest report reveals.
// specialCondition = contract landmine a solicitor review surfaces (surpriseCost if you never looked).

export const LISTINGS = [
  {
    id: 'weatherboard',
    address: '12 Banksia Street',
    style: 'Weatherboard cottage · c. 1925',
    saleType: 'auction',
    beds: 3, baths: 1, cars: 1, land: 512,
    guide: [780000, 850000],
    trueValue: 865000,
    reserve: 872000,
    repairCost: 8000,
    desc: 'Period charm on a north-facing block. Ornate ceilings, original floorboards, and a jacaranda out the back. Nothing to do but move in — or so the agent reckons.',
    agentWhy: 'Young family — they\'ve already bought in Wattlebrook East, settlement in eight weeks. They need a result on the day.',
    listedWeeks: 3,
    report: 'Structure sound. Minor rising damp in the laundry and two rotten veranda boards (~$8k). A tidy report — condition won\'t be your problem here; price might be.',
    specialCondition: null,
    palette: { wall: 0xe3ebee, roof: 0x8c3b2e, trim: 0xffffff, floor: 0xa8794f },
    lot: { x: -17, z: -42, facing: 1 },
  },
  {
    id: 'brick',
    address: '14 Banksia Street',
    style: 'Brick veneer · 1994 family home',
    saleType: 'private',
    beds: 4, baths: 2, cars: 2, land: 605,
    asking: 939000,
    guide: [939000, 939000],
    trueValue: 905000,
    vendorMin: 902000,
    reserve: 918000,
    repairCost: 3000,
    desc: 'Solid as the day it was built. Formal lounge, meals area, and a pergola built for Sunday snags. Walk to Wattlebrook Primary. Private sale — the vendors “aren’t in a hurry”.',
    agentWhy: 'Empty nesters heading to the Peninsula. No bridging loan, no mortgage, no hurry — they\'ll wait for their number.',
    listedWeeks: 6,
    report: 'Excellent condition for its age. Gutters need replacing (~$3k). Nothing structural — whether the asking price stacks up is a different question. Pull the comparable sales.',
    specialCondition: null,
    palette: { wall: 0xa85f46, roof: 0x53504a, trim: 0xf2ead9, floor: 0xc9b596 },
    lot: { x: -17, z: -14, facing: 1 },
  },
  {
    id: 'reno',
    address: '9 Banksia Street',
    style: '“Renovator’s delight” · original 1958',
    saleType: 'private',
    beds: 2, baths: 1, cars: 0, land: 560,
    asking: 655000,
    guide: [655000, 655000],
    trueValue: 640000,
    vendorMin: 618000,
    reserve: 655000,
    repairCost: 62000,
    desc: 'First time offered in 60 years! Bring your imagination (and your builder). Huge potential, sold as-is. Negotiable — the family “just wants it done”.',
    agentWhy: 'It\'s the grandmother\'s place — the family has been arguing about it for a year and they just want it done.',
    listedWeeks: 9,
    report: '⚠ Active termite damage in the subfloor, restumping required, wiring pre-dates decimal currency. Budget ~$62k before move-in — and make every dollar of that someone else\'s discount.',
    specialCondition: {
      clause: 'Sold strictly as-is: vendor gives no warranty that the rear extension was ever permitted. Your solicitor recommends a price allowance for rectification.',
      surpriseCost: 25000,
      surprise: 'Council has no permit for the rear extension — rectification order',
    },
    palette: { wall: 0xc9bda4, roof: 0x6e7062, trim: 0x8a8574, floor: 0x9c8f75 },
    lot: { x: -17, z: 14, facing: 1 },
  },
  {
    id: 'mcmansion',
    address: '11 Banksia Street',
    style: 'Rendered “executive residence” · 2016',
    saleType: 'auction',
    beds: 4, baths: 2, cars: 2, land: 480,
    guide: [940000, 990000],
    trueValue: 1010000,
    reserve: 1015000,
    repairCost: 5000,
    desc: 'Double-storey grandeur with a theatre room, butler’s pantry and zero eaves. The street’s trophy home — expect company on auction day.',
    agentWhy: 'The owners built again two suburbs over — bigger, of course. They\'d very much like their money out.',
    listedWeeks: 2,
    report: 'Near new. Minor render cracking (~$5k, cosmetic). The building is fine; the question is the land under it and the buyers beside you.',
    specialCondition: {
      clause: 'Title carries a sewerage easement across the rear 3 metres — nothing can ever be built over it. Priced in by those who read the Section 32.',
      surpriseCost: 15000,
      surprise: 'Sewer easement kills your future deck plans — value haircut',
    },
    palette: { wall: 0xe8e2d6, roof: 0x3a3f47, trim: 0x2f3640, floor: 0xd6cbb8 },
    lot: { x: 17, z: -28, facing: -1 },
  },
  {
    id: 'townhouse',
    address: '16 Banksia Street',
    style: 'Brand-new boutique apartment · never occupied',
    saleType: 'private',
    isNew: true,
    beds: 3, baths: 2, cars: 1, land: 240,
    asking: 749000,
    guide: [749000, 749000],
    trueValue: 745000,
    vendorMin: 738000,
    reserve: 745000,
    repairCost: 1000,
    desc: 'Never lived in — the developer’s last one. Priced at $749,000, conspicuously one dollar under the First Home Owner Grant cap. Comes with an owners corporation, which is a whole thing. Read the records.',
    agentWhy: 'Developer\'s last lot in the project. Their financier wants it off the books this quarter.',
    listedWeeks: 5,
    report: 'Brand new; only defect-period snags (~$1k). This report covers YOUR lot only — building-wide risk lives in the owners corporation records. NEW home: FHOG-eligible under $750k.',
    specialCondition: null,
    ownersCorp: {
      feesQtr: 890,
      records: 'OC certificate: fees $890/qtr. Sinking fund balance: $4,120 (thin for a new building). Minutes note the builder is in liquidation and a landscaping/waterproofing defect claim is unresolved — the committee has flagged a special levy of ~$7,500 per lot.',
      levy: 7500,
    },
    palette: { wall: 0x565b63, roof: 0x2c3037, trim: 0xd9c8a9, floor: 0xb8a184 },
    lot: { x: 17, z: 0, facing: -1 },
  },
  {
    id: 'bungalow',
    address: '7 Banksia Street',
    style: 'Californian bungalow · deceased estate',
    saleType: 'auction',
    beds: 3, baths: 1, cars: 1, land: 585,
    guide: [820000, 880000],
    trueValue: 900000,
    reserve: 895000,
    repairCost: 15000,
    desc: 'Held by one family since 1962. Leadlight windows, deep front veranda, established fruit trees. Deceased estate — it WILL be sold.',
    agentWhy: 'Deceased estate. The executor has court-approved instructions to sell. It WILL be sold, to someone.',
    listedWeeks: 4,
    report: 'Good bones. Roof tiles need re-bedding and the bathroom is tired (~$15k). Deceased estates often sell on the day — know your number before Saturday.',
    specialCondition: {
      clause: 'Deceased estate: the executor requires 30-day settlement and the contract excludes the usual chattels warranty. Fine if you know — a scramble if you don’t.',
      surpriseCost: 6000,
      surprise: 'Scrambling for 30-day settlement — bridging and rush fees',
    },
    palette: { wall: 0x9daf8e, roof: 0x7a4a35, trim: 0xf5efdd, floor: 0xa8794f },
    lot: { x: 17, z: 28, facing: -1 },
  },
];
